<?php
$language = "en";
  $array = [ 'Donald Trump','Friedrich Schiller','Buddha','Bob the Builder','Barack Obama','Yoda',
  'Spongebob','Johann Wolfgang von Goethe','Darth Vader','Jesus','Michael Jackson','Albert Einstein','Oscar Wilde','Sokrates','Dracula',
  'Scrooge McDuck','Neil Armstrong','Your Mother','Karl Marx','Kim Jong-un',
  'Britney Spears','Tom Cruise','Billie Eilish','Frank Sinatra','Lucky Luke','Pink Panther',
  'Bill Gates','Elon Musk','Isaac Newton','Mike Tyson','Dirk Nowitzki','James Bond','Günther Jauch','Erich Kästner','Steve Jobs',
  'James Bond','Kurt Cobain','Konstantin I. der Große','Karl der Große','Otto I. der Große','Death','Bud Spencer','Justin Timberlake','Ronaldo',
  'Prof. Dr. Christian Ernst','William Shakespeare','Joe Biden','Dr. Ing. Shirin Kadler','Dschingis Khan','Marco Polo','Nikola Tesla',
  'Vincent van Gogh','Pablo Picasso','Louis Armstrong','Walt Disney','Willy Brandt','Anne Frank','Muhammad Ali','Elvis Presley','Emanuel Lasker',
  'Refik Veseli','Sophie Scholl','Martin Luther','Johannes Gutenberg','Alexander von Humboldt','Christoph Kolumbus','Ludwig van Beethoven',
  'Helmut Schmidt','Michael Schumacher','Wilhelm Grimm','Steffi Graf','John F. Kennedy','Robert Koch','Dieter Bohlen','The Undertaker','Tupac Shakur',
  'Stefan Raab','Will Smith','Wladimir Putin','Stromberg','Arthur Schopenhauer','Wilhelm Busch','Dalai Lama','Eminem','Martin Luther King',
  'Hermann Hesse','Osho','Bruce Lee','Leonardo da Vinci','Stephen Hawking','Galileo Galilei','Paul Klee','Friedensreich Hundertwasser',
  'Stephen King','Konrad Adenauer','Wilhelm von Humboldt','Carl Benz','Batman','Sherlock Holmes','Superman','50 Cent','Anthony Accardo',
  'Wolfgang Schäuble','Friedrich Merz','Christian Solmecke','Lutz van der Horst','Sophie Charlotte von Hannover','Dome','Michael Müller',
  'Gaius Iulius Caesar','Kai Pflaume','Jacob Grimm',' Bertolt Brecht','Astrid Lindgren','Alexander der Große','George Washington',
  'Ungespielt','Knossi','Tom Cruise','Angelina Jolie','Brad Pitt','Beyoncé Knowles','George Clooney','Madonna','Leonardo DiCaprio',
  'Jennifer Lopez','Will Smith','Katy Perry','Johnny Depp','Taylor Swift','Robert Downey Jr.','Meryl Streep','Dwayne Johnson',
  'Jennifer Lawrence','Chris Hemsworth','Rihanna','Justin Bieber','Emma Watson','Mark Wahlberg','Selena Gomez','Hugh Jackman',
  'Scarlett Johansson','Chris Evans','Celine Dion','Eddie Murphy','Adele','Nicole Kidman','Ryan Reynolds','Julia Roberts','Chris Pratt',
  'Halle Berry','Matthew McConaughey','Charlize Theron','Daniel Radcliffe','Cameron Diaz','Adam Sandler','Anne Hathaway','Samuel L. Jackson',
  'Sandra Bullock','Bradley Cooper','Mila Kunis','Bruce Willis','Jennifer Aniston','Denzel Washington','Tom Hanks','Natalie Portman','Kevin Hart',
  'Alicia Keys','Jackie Chan','Emma Stone','Jamie Foxx','Steve Carell','Megan Fox','Channing Tatum','Michelle Obama','Sylvester Stallone','Angelica Huston',
  'Patrick Stewart','Kate Winslet','Ben Stiller','Sarah Jessica Parker','Robin Williams','Cate Blanchett','Russell Crowe','Kate Beckinsale','John Travolta',
  'Eminem','Ellen DeGeneres','Ricky Martin','Amy Adams','Stephen Curry','Zac Efron','Viola Davis','Ariana Grande','Will Ferrell','Amy Schumer','Colin Firth',
  'Kristen Stewart','Zoe Saldana','Jason Statham','Gwyneth Paltrow','Liam Neeson','Mila Kunis','Billie Eilish','Meryl Streep','James Franco','Reese Witherspoon',
  'Shakira','Tom Hardy','Demi Moore','Zendaya','Tom Holland','Rami Malek','Margot Robbie','Idris Elba','Jennifer Garner','Jonah Hill','Natalie Dormer',
  'Jeff Goldblum','Ralph Fiennes','Lupita Nyong"o"','Jake Gyllenhaal','Saoirse Ronan','Eva Green','Daisy Ridley','Jason Momoa','Oprah Winfrey','Melissa McCarthy',
  'Gal Gadot','Amanda Seyfried','Andrew Garfield','Timothée Chalamet','Chadwick Boseman','Emilia Clarke','Kit Harington','Michael B. Jordan','Tina Fey','Donald Glover',
  'Hailee Steinfeld','Tessa Thompson','Ansel Elgort','Priyanka Chopra','John Boyega','Lana Del Rey','Charlie Hunnam','Chris Pine','Jodie Foster','Ewan McGregor',
  'Jessica Chastain','Riz Ahmed','Ryan Gosling','Keanu Reeves','Lily Collins','Phoebe WallerBridge','Zendaya','Billie Eilish','Zoe Kravitz','Chris Rock','Joaquin Phoenix','Michael Fassbender','Margaret Qualley',
  'Wise men','Luke Skywalker','James Bond','Indiana Jones','Batman','SpiderMan','Captain America','Iron Man','Wonder Woman','Superman','Hermione Granger','Frodo Baggins','Gandalf','Darth Vader','Han Solo','Jack Sparrow',
  'Sherlock Holmes','Neo','Wolverine','Thor','Black Widow','Katniss Everdeen','Tony Stark','Ellen Ripley','The Joker','Princess Leia','John Wick','Lara Croft','Marty McFly','Ethan Hunt',
  'Black Panther','Dracula','Edward Scissorhands','The Terminator','Agent Smith','Rocky Balboa','John McClane','Forrest Gump','Deadpool','Jules Winnfield','Gollum','Vito Corleone',
  'Rick Deckard','Trinity','Don Vito Andolini','Maximus Decimus Meridius','Ellen Page','Atticus Finch','T`Challa','Michael Corleone','Jackie Chan','Katara','Jason Bourne',
  'Elle Woods','Shrek','Mulan','Leonardo DiCaprio','The Bride (Beatrix Kiddo)','Hannibal Lecter','Captain Jack Harkness','Ellie Sattler','Captain Marvel','Willy Wonka','The Dude (Jeffrey Lebowski)',
  'Jigsaw (John Kramer)','King Kong','R2D2','Aragorn','Marge Gunderson','Pennywise','Donnie Darko','Holly Golightly','Rocky Balboa','Donkey','Ellen Ripley','Norman Bates','Scarlett O´Hara','Harry Potter','Dory','Walter White','Freddy Krueger',
  'Jules Winnfield','John McClane','Gollum','Forrest Gump','Marty McFly','Maximus Decimus Meridius','Princess Leia','Batman','Superman','E.T'
  ];

  echo '- ' . $array[random_int(0, count($array) - 1)] . ' -' ;
?>
