<?php
$language = "de";
  $array = ['Die Welt ist flach!', 'We need to build a wall!', 'Das Internet ist Neuland für uns.','Ein Gespenst geht in Europa um,das Gespenst des Kommunismus.','Schön,die Phönizier haben das Geld erfunden. Aber warum so wenig?',
  'Niemand hat die Absicht, eine Mauer zu errichten.','Macht kaputt, was euch kaputt macht.','Sein oder nicht sein das ist hier die Frage!','Ich bin dein Vater.','Das Runde muss ins Eckige!',
  'Wer den Cent nicht ehrt, ist den Taler nicht wert.','Frei sein heißt, wählen können, wessen Sklave man sein will.' ,'Zwei Dinge sind unendlich: Das Universum und die menschliche Dummheit. Aber beim Universum bin ich mir nicht ganz sicher.',
  'Jedenfalls ist es besser, ein eckiges Etwas zu sein als nur ein rundes Nichts.','Männer wollen nicht die grosse Freiheit. Sie wollen viele kleine Freiheiten.','Das Leben formatiert, Geld kategorisiert.',
  'Der Vorteil der Klugheit besteht darin, dass man sich dumm stellen kann. Das Gegenteil ist schon schwieriger.','Wer kämpft, kann verlieren. Wer nicht kämpft, hat schon verloren.',
  'Man wird nicht dadurch besser, dass man andere schlecht macht.','Der Mensch hat dreierlei Wege klug zu handeln: erstens durch nachdenken, das ist der edelste, zweitens durch nachahmen, das ist der leichteste, und drittens durch Erfahrung, das ist der bitterste.',
  'Die meisten Menschen sind bereit zu lernen, aber nur die wenigsten, sich belehren zu lassen.','Eine Investition in Wissen bringt noch immer die besten Zinsen.',
  'Lache nie über die Dummheit der anderen. Sie ist deine Chance.','Wenn du den Humor verlierst, lachen die Anderen.','Sie lachen über mich, weil ich anders bin. Ich lache über sie, weil sie alle gleich sind.',
  'Reden ist Silber, Schweigen ist Gold.','Zieh aus allem negativen etwas positives.','Ich habe da ein ganz mieses Gefühl.','Stell dir vor, es ist Krieg und keiner geht hin.',
  'Je öfter eine Dummheit wiederholt wird,desto mehr bekommt sie den Anschein der Klugheit.','Hit me baby one more time.','Ich will der allerbeste sein.','Wer seine Zunge hütet vermeidet manchen Konflikt.',
  'Worte sind nur die Verpackung, aber Taten sind das Geschenk.','Wenn du aufhörst zu lernen, fange an, dich zu verändern.','Glücklichsein ist kein Zustand, sondern eine Fähigkeit.',
  'Als erstes lasst uns alle Anwälte umbringen.','Was Recht ist, muss nicht gerecht sein.','Das Leben ist ungerecht, leider zu oft in dieser reichen Welt.',
  'Der Blick in die Zukunft ist nur in der Gegenwart möglich.','Wo die Zeit bleibt mag kaum jemand zu sagen.','Im Licht der Unsichtbaren wird man schnell sichtbar.',
  'Wenn ich unabhängig bin, kann ich frei wählen.','Wer das Herz berührt, trifft auch die Seele.','Erfolg beginnt im Kopf.','Netzwerk ist Alles. Alles ohne Netzwerk wird zu Nichts.',
  'Ordnung basiert auf Entscheidungen.','Das kleinste Ego erkennst du immer an den größten Lügen.','Wenn Du alles hast, kommt der Rest von ganz allein.','Sowie ein Zweiter mit an Bord ist, ist der Schuld.',
  'Ein Mensch ist kein Mensch, nur weil er ein Mensch ist.','Allein kann man alles richtig machen und doch ist es falsch.','Du bist erst selbständig, wenn Du Dich selbst ständig von Deinem selbst verdienten Geld ernähren kannst.',
  'Das Geht Doch Nicht!','Überlege einmal, was du denkst. Überlege zweimal, was du sagst. Überlege dreimal, was du tust.','Jede Sprache ist eine Programmiersprache.','Die meisten Träume entstehen im Schlaf, die wirklich interessanten im wachen Kopf.',
  'Houston, wir haben ein Problem.','Oft verliert man das Gute, wenn man das Bessere sucht.','Wer aufhört, besser zu werden, hat aufgehört, gut zu sein.',
  'Dem, der uns Gutes tut, sind wir nie so dankbar wie dem, der uns Böses tun könnte, es aber unterlässt.','Gutes kann niemals aus Lüge und Gewalt entstehen.',
  'Wir denken selten an das, was wir haben, aber immer an das, was uns fehlt.','Du siehst die Welt nicht so wie sie ist, du siehst die Welt so wie du bist.',
  'Dumme Gedanken hat jeder, aber der Weise verschweigt sie.','Diejenigen die wir lieben, können uns am meisten verletzen.','Am schlimmsten ist die Einsamkeit zu zweit.',
  'Ich wars nicht.','Es schneit und friert in New York. Wir brauchen globale Erwärmung!','Make America great again!','Was machst du denn?','Ich habe einen Traum.', 'Sei die Veränderung, die du in der Welt sehen willst.', 'Ich denke, also bin ich.', 'Das Leben ist wie eine Schachtel Pralinen, man weiß nie, was man bekommt.', 'Wir können nicht unser Schicksal ändern. Wir können nur entscheiden, wie wir damit umgehen.', 'Es gibt keine Leidenschaft, die nicht respektabel wäre, außer die für Dummheit.', 'Die größte Sehenswürdigkeit, die es gibt, ist die Welt - sieh sie dir an.', 'Ich glaube an rosa Lippenstift.', 'Ich habe nie versucht, etwas anderes zu sein als eine Schauspielerin.', 'Nur wer sein Ziel kennt, findet den Weg.', 'Wenn du schnell gehen willst, geh alleine. Wenn du weit gehen willst, geh mit anderen.', 'Die Dinge ändern sich. Und manchmal ändern sie sich sehr schnell. Das ist das Leben.', 'Jeder Tag ist eine neue Chance, das zu tun, was du liebst.', 'Wer nicht neugierig ist, erfährt nichts.', 'Liebe ist das, was wir am meisten brauchen, um glücklich zu sein.', 'Der größte Ruhm im Leben besteht nicht darin, niemals zu fallen, sondern jedes Mal wieder aufzustehen.', 'Das Leben ist wie Fahrradfahren. Man muss sich vorwärts bewegen, um das Gleichgewicht zu halten.', 'Gib niemals auf, denn jeder Tag ist eine neue Chance, um dein Leben zu ändern.', 'Eine Sache des Herzens kann man nicht beschreiben, man kann sie nur spüren.', 'Es ist nicht wichtig, wie hart man schlägt. Es zählt nur, wie hart man getroffen werden kann und trotzdem weitermacht.', 'Das Wichtigste im Leben ist es, nicht aufzuhören, Fragen zu stellen.', 'Glück ist nicht das, was du bekommst, wenn du bekommen, was du willst. Es ist das Gefühl, das du hast, wenn du dich schätzt.', 'Zweifle nie daran, dass eine kleine Gruppe engagierter Menschen die Welt verändern kann. Tatsächlich ist es das Einzige, was jemals passiert ist.', 'Die wertvollste Währung im Leben ist Zeit. Verwende sie klug.', 'Die Zukunft gehört denen, die an die Schönheit ihrer Träume glauben.', 'Glaube an dich selbst und alles wird möglich sein.', 'Jede Minute, die du verärgert verbringst, ist 60 Sekunden verlorenes Glück.', 'Es gibt nichts Schöneres als jemanden zu lieben und geliebt zu werden.', 'Nur wer sein Ziel kennt, findet den Weg.', 'Nichts in der Welt ist so mächtig wie eine Idee, deren Zeit gekommen ist.', 'Wenn du eine Veränderung in der Welt sehen willst, sei die Veränderung.', 'Das Leben ist zu kurz, um das zu tun, was alle anderen von dir erwarten.', 'Du musst der Wandel sein, den du in der Welt sehen willst.', 'Wir sind das, was wir immer wieder tun. Exzellenz ist daher keine Handlung, sondern eine Gewohnheit.'




  ];

  echo '"' . $array[random_int(0, count($array) - 1)] . '"';
?>
